### ISSUE TITLE
missing dependency on newick?

### ISSUE THREAD

**Issue by grahamgower** [conda-forge/msprime-feedstock#64]
`setup.cfg` has newick as a listed dependency. I see this is a "soft" dependency, in the sense that failure to import just limits feature availablility (in `msprime/species_trees.py`). But it means that `pip check` fails after installing the msprime conda package. Probably its fine to just add it to the conda recipe `run:` dependencies?

**Comment by grahamgower** [comment]
Oh, and maybe add a `pip check` to the `test:` section of the recipe. FYI, [grayskull](https://github.com/conda-incubator/grayskull) adds a  `pip check` test by default, which is how I found this issue.

**Comment by jeromekelleher** [comment]
Hmm, not sure how this one crept past. Unfortunately there's no conda-forge package for ``newick``, so it's not straightforward to put in a dependency.

I guess we could add it as an optional dependency in the ``setup.cfg``? I doubt it's used much.

**Comment by matthewfeickert** [comment]
> I guess we could add it as an optional dependency in the `setup.cfg`? I doubt it's used much.

@conda-forge/msprime As https://github.com/tskit-dev/msprime/ still [depends on `newick`](https://github.com/tskit-dev/msprime/blob/1b14a8a43cee4a0d57ba0c9878955da1d3699bc8/pyproject.toml#L37) is `newick` actually an optional dependency for `msprime` that isn't being treated as such? Or is it used in the core library? (No judgement, just curiosity here, given the situation in https://github.com/conda-forge/staged-recipes/pull/27252#discussion_r3192280930).

As I suggested on the `spaceprime` PR, have you contacted the maintainers https://gitlab.mpcdf.mpg.de/dlce-eva/python-newick to ask if they would be open to getting `newick` on conda-forge? I'll also point out that `newick` has an infrequent release cycle (https://gitlab.mpcdf.mpg.de/dlce-eva/python-newick/-/tags) compared to `msprime` (https://github.com/tskit-dev/msprime/releases) so submitting the recipe yourselves would be a low maintenance burden.

**Comment by petrelharp** [comment]
I'm trying to find a formal definition for 'optional dependency', but I think 'yes' because: if `newick` is needed by a function the user calls (which is uncommon) then we raise [this informative exception](https://github.com/tskit-dev/msprime/blob/1b14a8a43cee4a0d57ba0c9878955da1d3699bc8/msprime/species_trees.py#L39).

Right now `newick` is listed as a dependency [in `pyproject.toml`](https://github.com/tskit-dev/msprime/blob/1b14a8a43cee4a0d57ba0c9878955da1d3699bc8/pyproject.toml#L37); it looks from [these docs](https://conda-forge.org/docs/how-to/basics/populate-dependencies/#pyprojecttoml) that we could move it to `optional-dependencies`. However, after I do this, `pip check` still gives the same error as before (`msprime 1.3.4 requires newick, which is not installed.`).

Do you know the right way to deal with this?

**Comment by matthewfeickert** [comment]
> I'm trying to find a formal definition for 'optional dependency', but I think 'yes' because: if `newick` is needed by a function the user calls (which is uncommon) then we raise [this informative exception](https://github.com/tskit-dev/msprime/blob/1b14a8a43cee4a0d57ba0c9878955da1d3699bc8/msprime/species_trees.py#L39).

Thanks @petrelharp. That does sound like an optional dependency, that you could do something like

```toml
[project.optional-dependencies]
newick = ["newick>=1.3.0"]
```

in `msprime`'s `pyproject.toml`.

> However, after I do this, `pip check` still gives the same error as before (`msprime 1.3.4 requires newick, which is not installed.`).

[`pip check`](https://pip.pypa.io/en/latest/cli/pip_check/) will

> Verify installed packages have compatible dependencies.

so whatever version of `msprime` that you have installed in the environment that you're running `pip check` in still has `newick` listed in its metadata. You would need to reinstall this to get the correct metadata (assuming we're talking about a Python virtual environment).

For this feedstock, any change without patching would require a new release to be made of `msprime`. However, as this is conda-forge, you can add a patch that simply patches out `newick` from `msprime` `v1.4.1`'s `pyproject.toml`

```console
$ git clone git@github.com:tskit-dev/msprime.git && cd msprime && git checkout 1.4.1 -b patch-1-4-1 && sed -i '/"newick>=1.3.0",/d' pyproject.toml && git add pyproject.toml && git commit -m "FIX: Patch out optional dependency newick" && git format-patch -1 HEAD
0001-FIX-Patch-out-optional-dependency-newick.patch
```

add it to the feedstock recipe and rebuild.

**Comment by jeromekelleher** [comment]
We took a pragmatic approach to packaging for the ``newick`` module, as it's a very rarely used feature of msprime. I don't think it's worth updating msprime's pyproject.toml to make it an optional dependency TBH (but if someone wants to do the legwork I'd be happy to accept a PR). 

I agree the right thing to do here would be to package ``newick`` on conda-forge and have an explicit dependency on it for msprime's feedstock.

**Comment by jeromekelleher** [comment]
Having seen the downstream complexity that this is causing, I'd be happy to change "newick" to an optional dependency for msprime (slightly contrary to my last comment!). Would that then remove the block on the spaceprime etc packages @matthewfeickert ? It really isn't necessary to package ``newick`` for conda I think, it's only supporting one quite obscure feature.

**Comment by matthewfeickert** [comment]
> I'd be happy to change "newick" to an optional dependency for msprime (slightly contrary to my last comment!). Would that then remove the block on the spaceprime etc packages?

Thanks @jeromekelleher. Yes, that would resolve things, but as you point out

> I agree the right thing to do here would be to package newick on conda-forge and have an explicit dependency on it for msprime's feedstock.

would also resolve things and both are about the same amount of effort. (The recipe for `newick` seems like it should be very easy. The "issue" is who will agree to be a maintainer in this approach.)

I took this opportunity to cross-reference metadata emails to find that @xrotwang is the maintainer of https://gitlab.mpcdf.mpg.de/dlce-eva/python-newick. 👋 @xrotwang, would you be open to `newick` being added to conda-forge with you listed as a maintainer? 

**edit**: Here is the recipe file for `newick`

<details>
<summary>recipe.yaml:</summary>

```yaml
schema_version: 1

context:
  version: "1.11.0"
  python_min: "3.8"

package:
  name: newick
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/newick/newick-${{ version }}.tar.gz
  sha256: b8bf81f88dbc0e1cb85928e6f4c7e0e29062c3739e27216aae76c3065a297186

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - newick
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A python module to read and write the Newick format
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://gitlab.mpcdf.mpg.de/dlce-eva/python-newick
  repository: https://gitlab.mpcdf.mpg.de/dlce-eva/python-newick
  documentation: https://gitlab.mpcdf.mpg.de/dlce-eva/python-newick

extra:
  recipe-maintainers:
    - xrotwang
```

</details>
